FROM openjdk:17-jre-slim

WORKDIR /app

# Kopiere die korrekte JAR
COPY target/marktsimulation-1.0.0-jar-with-dependencies.jar app.jar
COPY config/config.properties config/

EXPOSE 5556

# Starte mit mode parameter
ENTRYPOINT ["java", "-jar", "app.jar", "--mode=seller"]